// Builds the internal escalation email. Pure + server-safe: it holds no
// secrets and never references the recipient or API key (those live in env and
// are applied by the API route). The recipient is ALWAYS the internal manager,
// never the customer.

export interface EscalationChecklistItem {
  label: string;
  flagged?: boolean;
}

export interface EscalationPayload {
  caseId: string;
  customerRef: string;
  issueType: string; // human label
  risk: string; // "low" | "medium" | "high" | "critical"
  assignedTeam: string;
  status: string;
  internalNote: string;
  checklist: EscalationChecklistItem[];
  managerAction: string;
}

export interface BuiltEmail {
  subject: string;
  html: string;
  text: string;
}

function cap(s: string): string {
  if (!s) return "—";
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function esc(s: string): string {
  return String(s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

export function buildEscalationEmail(p: EscalationPayload): BuiltEmail {
  const caseId = p.caseId || "—";
  const riskLabel = cap(p.risk);

  const subject = `Escalation: ${caseId} · ${p.issueType} · ${riskLabel} risk`;

  const rows: [string, string][] = [
    ["Case ID", caseId],
    ["Customer reference ID", p.customerRef || "—"],
    ["Issue type", p.issueType || "—"],
    ["Risk level", riskLabel],
    ["Assigned team", p.assignedTeam || "—"],
    ["Current status", p.status || "—"],
  ];

  // ----- HTML -----
  const rowsHtml = rows
    .map(
      ([k, v]) =>
        `<tr><td style="padding:6px 12px;color:#9094a0;font-size:13px;white-space:nowrap;">${esc(
          k,
        )}</td><td style="padding:6px 12px;color:#16181b;font-size:13px;font-weight:600;">${esc(
          v,
        )}</td></tr>`,
    )
    .join("");

  const checklistHtml = p.checklist.length
    ? `<ul style="margin:8px 0 0;padding-left:18px;color:#16181b;font-size:13px;line-height:1.6;">${p.checklist
        .map(
          (c) =>
            `<li>${c.flagged ? "▲ " : ""}${esc(c.label)}</li>`,
        )
        .join("")}</ul>`
    : `<p style="color:#9094a0;font-size:13px;">No checklist items.</p>`;

  const html = `<!doctype html><html><body style="margin:0;background:#f4f4f5;padding:24px;font-family:Arial,Helvetica,sans-serif;">
  <div style="max-width:640px;margin:0 auto;background:#ffffff;border:1px solid #e5e7eb;border-radius:12px;overflow:hidden;">
    <div style="background:#14161b;padding:18px 20px;">
      <div style="color:#c9a24b;font-size:12px;letter-spacing:.08em;text-transform:uppercase;font-weight:700;">Internal escalation</div>
      <div style="color:#ffffff;font-size:17px;font-weight:700;margin-top:2px;">${esc(
        caseId,
      )} — ${esc(p.issueType)}</div>
    </div>
    <div style="padding:20px;">
      <table style="border-collapse:collapse;width:100%;border:1px solid #eee;border-radius:8px;">${rowsHtml}</table>

      <h3 style="font-size:12px;letter-spacing:.06em;text-transform:uppercase;color:#9094a0;margin:20px 0 6px;">Internal note</h3>
      <pre style="white-space:pre-wrap;font-family:ui-monospace,Menlo,Consolas,monospace;font-size:12px;color:#16181b;background:#f7f7f8;border:1px solid #eee;border-radius:8px;padding:12px;margin:0;">${esc(
        p.internalNote,
      )}</pre>

      <h3 style="font-size:12px;letter-spacing:.06em;text-transform:uppercase;color:#9094a0;margin:20px 0 6px;">Escalation checklist</h3>
      ${checklistHtml}

      <div style="margin-top:20px;border:1px solid #c9a24b;background:#fbf6e9;border-radius:8px;padding:14px;">
        <div style="font-size:12px;letter-spacing:.06em;text-transform:uppercase;color:#8c7434;font-weight:700;">Recommended manager action</div>
        <div style="font-size:14px;color:#16181b;margin-top:4px;line-height:1.5;">${esc(
          p.managerAction,
        )}</div>
      </div>

      <p style="margin:20px 0 0;font-size:11px;color:#9aa0aa;line-height:1.5;">
        Internal escalation notice — for the support manager only. Do not forward to the customer.
        Generated by the Support Reply Generator from sample data.
      </p>
    </div>
  </div>
</body></html>`;

  // ----- Plain text -----
  const text = [
    `INTERNAL ESCALATION`,
    ``,
    ...rows.map(([k, v]) => `${k}: ${v}`),
    ``,
    `Internal note:`,
    p.internalNote,
    ``,
    `Escalation checklist:`,
    ...(p.checklist.length
      ? p.checklist.map((c) => `- ${c.flagged ? "(!) " : ""}${c.label}`)
      : ["- (none)"]),
    ``,
    `Recommended manager action:`,
    p.managerAction,
    ``,
    `— Internal only. Do not forward to the customer. Sample data.`,
  ].join("\n");

  return { subject, html, text };
}
